#!/usr/bin/env python3

import time
from random import randint
import unicornhat as unicorn
from weather import Weather
import pics.py

unicorn.set_layout(unicorn.AUTO)
unicorn.rotation(0)
uniconr.brightness(0.175)
uh_width,uh_height=unicorn.get_shape()

def drawPic(pic):
    

def weatherUpdate():
    weather = Weather()
    location = weather.lookup_by_location('tampere')
    condition = location.condition()
    return condition

wet = weatherUpdate()
unicornhat.set_layout(sun)
