#!/usr/bin/env python3

from time import sleep
from random import randint
import unicornhat as unicorn
from weather import Weather
from pics import Pics

unicorn.set_layout(unicorn.AUTO)
unicorn.rotation(0)
unicorn.brightness(0.175)
uh_width,uh_height=unicorn.get_shape()

def drawPic(pic):
    for h in range(uh_height):
        for w in range(uh_width):
            unicorn.set_pixel(w, h, pic[h][w][0], pic[h][w][1], pic[h][w][2])
    unicorn.show()

def weatherUpdate():
    weather = Weather()
    location = weather.lookup_by_location('tampere')
    condition = location.condition()
    return condition

wet = weatherUpdate()
while True:
    drawPic(Pics.one)
    sleep(2)
